- src/entities.py
In the `gh-pages` history, we have lots of commits only changing the order of the ingredients over and over again (e.g. 8734d36).
In this PR, I sort the list of Ingredients in the JSON Output to prevent the changes to a new random order every time we run the parser.
> Sort ingredients in JSON Output

- src/entities.py
- src/main.py
Fixes #23.
In case there is no price available, like shown here:
```JSON
"prices": {
"students": {
"base_price": "N/A",
"price_per_unit": null,
"unit": null
},
"staff": {
"base_price": "N/A",
"price_per_unit": null,
"unit": null
},
"guests": {
"base_price": "N/A",
"price_per_unit": null,
"unit": null
}
}
```
We set the complete `Price` object to `null`.
```JSON
"prices": {
"students": null,
"staff": null,
"guests": null,
}
```
Besides that, every generated JSON file now has a `version` attribute in its first level.
This version will be incremented each time the JSON format changes.
Example:
```JSON
{
"number": 42,
"year": 2021,
"days": [],
"version": 2.1
}
```
> Fix for Mixed Types in Prices

- src/test/test_menu_parser.py
- src/test/test_util.py
Refactoring of StudentenwerkMenuParserTest
Preparation to extend test cases to #33 
One `pytest` fails but it already failed in the same way before.
WIP because black fails for the last commit with the following error:
```
black....................................................................Failed
- hook id: black
- files were modified by this hook
reformatted /home/lukas/PycharmProjects/eat-api/src/test/test_menu_parser.py
All done! ✨ 🍰 ✨
1 file reformatted, 1 file left unchanged.
```
Does anyone have an idea where it comes from?
> refactor StudentenwerkMenuParserTest

- js/app.js
This PR fixes an issue, where Safari browser were not able, to get the date from the URL.
Further, an other bug is fixed: When the date parameter in the URL doesn't represent a date, it now falls back to the current day. Before, the website didn't show anything anymore.
> Safari Fix

- css/styles.css
- js/app.js
This PR includes some UI fixes regarding the map on the website.
- Make the map in the modal larger, especially on large screens
- Stop loading animation for the location button, when permission is denied + show error message
- Increase contrast of the closing sign for the modals
> Website - UI Fixes - Location/Map

- js/app.js
This is a quick bug fix, to make menus viewable again on the eat-api website, as it is currently broken as mentioned in #79.
This makes it only possible to see the most recent menus.
I would propose to proceed, and load the correct labels enum json files together with the merge of the modules.
Otherwise I would have to do it almost twice, once without the modules and then once again with the modules.
Here another question: should I handle the new labels format as well as the old ingredients format? Or is it sufficient, that it won't break with the old ingredients, but also no further info? Or how would you handle this?
Additionally, I'm not sure how Git will handle this, because there is no a revert commit, and I already based other PRs on the modules?
Or do you think, we shouldn't …
> Website - Quick Bugfix: Make menus viewable again

- js/app.js
This PR resolves #79
- Load the `canteens.json` from the `enum` folder
- Load `labels.json`
- Show new labels format, and don't break when no labels are available (e.g. only ingredients on old dish plans)
The website now looks like this:
With the information looking like this:
I already opened an issue, regarding shorter labels/emojis  (#81) and will extend the website, once this is done.
> Website - Fix labels

- src/entities.py
This PR resolves #86 
The following things are included:
- Add english translations for labels (ingredients)
- Add english to languages
- Add additional fields to languages: base_url (of the API), a symbol and a label (language name in given language)
- Rename `enum_name` field to `name` (I think, this is not yet adapted from other services accessing the API, so it should be possible to change it)
> Update languages enum, add label translations

- src/entities.py
Resolves #74 
Adds the queue status API as described to the canteens enum, and also to the `canteens.json` in the output
> Add queue status field to the canteens and set it for "mensa-garching"

- js/components/labels.js
- js/components/menu.js
- js/modules/url-utils.js
This PR includes a new functionality, to filter dishes based on their ingredients, as mentioned in https://github.com/TUM-Dev/eat-api/issues/27#issuecomment-977925292 so this should resolve #27.
It should be possible, to filter out dishes containing one of the given ingredients. Currently, this is possible via the modal, which opens up, when clicking on the info icon besides the _Dish_ headline.
The user interface is like this, when hiding dishes _with preservative_ and _with flavor enhancers_:
Additionally, the url is changed accordingly, the search path for the figure above is: `?filter%5B0%5D=2&filter%5B1%5D=4` (readable: `?filter[0]=2&filter[1]=4`)
I think the placement of the filters is not ideal, however I have not come up with a better idea yet.
Further, due to some internal …
> Ingredient selection for website

- src/entities.py
As the API can have different deployment targets, I think it is more useful, to provide only a relative path for the base of each language.
This is especially useful, when developing the local website (with local API) so that no references to the public API are used.
> Update base_url to only include relative path

- scripts/parse.sh
This PR resolves #94 
Due to some refactoring in the parsing script, the language parameter got lost.
This resulted in german dish titles in the english API.
Here, the parameter is introduced again, and therefore future updates should be correct again.
> Fix missing translations

- scripts/parse.sh
- scripts/parse_canteen_list.py
Resolves #70
Instead of having a separate list of canteens in the `parse.sh` script, this allows to reuse the command from the `main.py`
I also thought about adding an option to parse all canteens at once, however, then we would loose the benefit of executing all script at the same time.
> Remove duplicate mentioning of canteens in parse script

- js/components/menu.js
Resolves #102 
Don't add a "/" to the URL after the base path -> fixes german, as URL should be relative not absolute
Remove unneccessary language parameter from URL
> [website] Fix URL for accessing menu data with different languages

- js/components/labels.js
This PR includes the symbols/abbreviations on the website again, as implemented through #85 
Additionally, I fixed a bug, where `labels.json` was loaded several times at the beginning.
> [website] symbols and abbreviations for labels

- .github/workflows/swagger.yml
- README.md
- openapi.yml
This PR resolves #98 
---
Here I added a documentation of the API with respect to the OpenAPI specification (https://swagger.io/specification/).
I added the specification file to the master branch (instead of the `gh-pages`). So changes to the API (via code) can be directly reflected in the documentation as well.
To access it, I want to provide it via the Github pages, in a subfolder. So the URL would be: https://tum-dev.github.io/eat-api/swagger-ui . I chose a subdirectory, as via  https://tum-dev.github.io/eat-api is the website version accessible. 
When implemented I can add a reference on the website to the documentation.
I added a workflow, that creates a PR whenever new changes of the specification file (`openapi.yml`) are pushed to the master branch. Such a PR will look like this: …
> Add documentation via swagger

- openapi.yml
- src/entities.py
Resolves #89 
---
Here I added static open hours to all canteens manually, according to the page: https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/muenchen/
I was also trying on parsing the page, however there are different pages for different canteens, and these often only contain the name as reference to a canteen, which seemed error prone to me.
Additionally, there is no unified way on presenting the open hours on the webpage e.g.:
Besides the different times given, the format sometimes includes whitespaces or different kinds of separators ("–", "-")
I thought, the times won't change that often, and therefore static open hours should be sufficient.
If you have any other idea, on how to approach this, I would be happy to know it.
Example in `canteens.json` …
> Introduce static open hours for canteens

- js/components/menu.js
Currently, there is a small bug, when changing the language, the menu gets only updated after a reload of the menu.
This PR fixes this issue.
Before (with page reload): 
Now:
> Fix: change dish title immediately, when changing the language

- openapi.yml
- src/entities.py
Resolve an issue regarding PR #117  
Previous URL pointed to a 301 redirect, to the new URL
This could be a problem, as there is no CORS present for the 301 redirect, and therefore a browser can't follow to the new URL.
> Fix url for mensa garching queue status API

- css/styles.css
- js/app.js
- js/components/labels.js
- js/components/location-selection.js
- js/components/modal.js
- js/components/opening-hours.js
- js/modules/date-utils.js
- js/modules/translation.js
Resolves #114 
Ready for merge after #105 
Displays the opening hours for a canteen on the gh-pages website.
This looks currently as follows:
The text can have different colors:
- red, when the canteen already closed
- green, when the canteen is open
- blue, when the canteen will open today
- black, when the selected day is not today
Further, a click on the info icon will open a modal, that shows all opening hours for the given canteen:
> [Website] Show opening hours

- src/menu_parser.py
Adapted all hardcoded price values to their new values after the price increase (15.6).
For the cafeterias Garching, Weihnstephan and Lohelstraße the new prices can be found [here](https://www.studentenwerk-muenchen.de/mensa/mensa-preise/).
> Adapt to price changes

- src/test/assets/studentenwerk/mensa-arcisstr/reference/combined.json
- src/test/assets/studentenwerk/mensa-garching/reference/combined.json
- src/test/assets/studentenwerk/mensa-garching/reference/week_37.json
- src/test/assets/studentenwerk/mensa-garching/reference/week_38.json
- src/test/assets/studentenwerk/stubistro-grosshadern/reference/combined.json
- src/test/test_menu_parser.py
This PR repairs the tests that have failed to pass since the [PR](https://github.com/TUM-Dev/eat-api/pull/155). For this, all prices have been adjusted to the new values.
> Adapt Tests to Price Changes

- src/entities.py
- src/menu_parser.py
Added the [stucafe Connollystraße](https://www.studentenwerk-muenchen.de/stucafe-olympiapark/) to the list of all cafeterias.
Since it uses the same template for mealplans, no parser had to be adapted.
The mealplan can be found [here](https://www.studentenwerk-muenchen.de/mensa/speiseplan/speiseplan_425_-de.html).
The coordinates are defined with the help of [maps](https://www.google.com/maps/@48.1793532,11.5465894,19z).
> Add Stucafe Connollystraße

- README.md
- src/menu_parser.py
The stuwerk changed their domain to [studierendenwerk-muenchen-oberbayern.de](https://www.studierendenwerk-muenchen-oberbayern.de/). Currently there is a redirect in place, this PR adds the updated URL in case the redirect stops working some time.
> New stuwerk URL

- src/entities.py
The opening hours for the Mensa Garching have changed a while ago.
This PR updates the opening hours on days Monday to Thursday from 11:00-14:00 to 11:00-14:**30** according to the [website of the "Studierendenwerk"](https://www.studierendenwerk-muenchen-oberbayern.de/mensa/standorte-und-oeffnungszeiten/garching/).
> update opening hours for Mensa Garching

- scripts/reformat.py
- src/entities.py
- src/menu_parser.py
- src/test/test_menu_parser.py
Fixes #257 by using the overview instead of the daily details pages
> Fix StudentenWerkMenuParser

- src/entities.py
We made an api for some canteens of the "Hochschule München". The API scheme is compatible with the currently present one on MENSA_GARCHING
> Add capacity api for some hochschul-canteens

- pyproject.toml
- src/entities.py
this changes dependencies from poetry specific format into the general python one
Poetry can only use this format since its version 2.
see https://packaging.python.org/en/latest/guides/writing-pyproject-toml, [dev deps](https://packaging.python.org/en/latest/specifications/dependency-groups/), [Poetry setup](https://python-poetry.org/docs/basic-usage/#project-setup)
> Update Python.toml 

- scripts/parse.sh
- scripts/parse_canteen_list.py
- src/cli.py
- src/main.py
Fixes #282 by directly providing a `--canteen-ids` parameter that prints canteen id and exits.
That way we do not have to rely on the additional parser script that can handle only stdin input.
Fixes the following CI crash:
```
Traceback (most recent call last):
File "/home/runner/work/eat-api/eat-api/scripts/parse_canteen_list.py", line 7, in <module>
canteens = json.load(sys.stdin)
^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/json/__init__.py", line 293, in load
return loads(fp.read(),
^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/json/decoder.py", line 337, in …
```
> More reliable and simpler canteen list handling

- .github/workflows/ci.yml
CodeQL complains about this not being here and it somewhat makes sense to add it.
This PR also remvoes the pre-commit from CI as we are now running this a different way
> chore: add permissions block to CI
